INSERT INTO source (source) VALUES
('Google Books'),
('IRUS-UK'),
('JSTOR'),
('OAPEN'),
('Open Book Publishers HTML Reader'),
('Open Book Publishers PDF Reader'),
('Open Book Publishers'),
('Open Edition'),
('OpenAIRE'),
('SUB Göttingen'),
('The Classics Library'),
('Ubiquity Press'),
('Unglue.it'),
('Wikimedia'),
('World Reader'),
('Εθνικό Κέντρο Τεκμηρίωσης');
