INSERT INTO measure (measure_uri, namespace, source, type, version) VALUES
('https://metrics.operas-eu.org/google-books/views/v1', 'https://metrics.operas-eu.org', 'Google Books', 'views', 'v1'),
('https://metrics.operas-eu.org/obp-html/sessions/v1', 'https://metrics.operas-eu.org', 'Open Book Publishers HTML Reader', 'sessions', 'v1'),
('https://metrics.operas-eu.org/obp-pdf/sessions/v1', 'https://metrics.operas-eu.org', 'Open Book Publishers PDF Reader', 'sessions', 'v1'),
('https://metrics.operas-eu.org/obp/downloads/v1', 'https://metrics.operas-eu.org', 'Open Book Publishers', 'downloads', 'v1'),
('https://metrics.operas-eu.org/world-reader/users/v1', 'https://metrics.operas-eu.org', 'World Reader', 'users', 'v1'),
('https://metrics.operas-eu.org/world-reader/pageviews/v1', 'https://metrics.operas-eu.org', 'World Reader', 'pageviews', 'v1'),
('https://metrics.operas-eu.org/open-edition/views/v1', 'https://metrics.operas-eu.org', 'Open Edition', 'views', 'v1'),
('https://metrics.operas-eu.org/open-edition/downloads/v1', 'https://metrics.operas-eu.org', 'Open Edition', 'downloads', 'v1'),
('https://metrics.operas-eu.org/oapen/downloads/v1', 'https://metrics.operas-eu.org', 'OAPEN', 'downloads', 'v1'),
('https://metrics.operas-eu.org/jstor/views/v1', 'https://metrics.operas-eu.org', 'JSTOR', 'views', 'v1'),
('https://metrics.operas-eu.org/jstor/downloads/v1', 'https://metrics.operas-eu.org', 'JSTOR', 'downloads', 'v1'),
('https://metrics.operas-eu.org/classics-library/sessions/v1', 'https://metrics.operas-eu.org', 'The Classics Library', 'sessions', 'v1'),
('https://metrics.operas-eu.org/unglueit/downloads/v1', 'https://metrics.operas-eu.org', 'Unglue.it', 'downloads', 'v1'),
('https://metrics.operas-eu.org/openaire/downloads/v1', 'https://metrics.operas-eu.org', 'OpenAIRE', 'downloads', 'v1'),
('https://metrics.operas-eu.org/irusuk/downloads/v1', 'https://metrics.operas-eu.org', 'IRUS-UK', 'downloads', 'v1'),
('https://metrics.operas-eu.org/wikimedia/views/v1', 'https://metrics.operas-eu.org', 'Wikimedia', 'views', 'v1'),
('https://metrics.operas-eu.org/sub-gottingen/downloads/v1', 'https://metrics.operas-eu.org', 'SUB Göttingen', 'downloads', 'v1'),
('https://metrics.operas-eu.org/ekt/downloads/v1', 'https://metrics.operas-eu.org', 'Εθνικό Κέντρο Τεκμηρίωσης', 'downloads', 'v1');
